server:
  port: 8080

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATA_SOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

bot:
  name: ParcelLoaderBot
  key: ${TELEGRAM_BOT_TOKEN}